### ISSUE TITLE
[0.19.4] Strange problem with command w/o options

### ISSUE THREAD

**Issue by EnochTheWise** [devops-works/binenv#214]
```
$ dive
binenv lets you install binary-distributed applications
(e.g. terraform, kubectl, ...) easily and switch between any version.

If your directory has a '.binenv.lock', proper versions will always be
selected.

Usage:
  binenv [flags]

Flags:
  -B, --bindir string     binaries directory [BINENV_BINDIR] (default "/home/john/.binenv/")
  -K, --cachedir string   cache directory [BINENV_CACHEDIR] (default "/home/john/.cache/binenv")
  -C, --confdir string    distributions configuration directory [BINENV_CONFDIR] (default "/home/john/.config/binenv")
  -g, --global            global mode [BINENV_GLOBAL]
  -h, --help              help for binenv
  -L, --linkdir string    link directory [BINENV_LINKDIR] (default "/home/john/.binenv/")
  -v, --verbose           verbose operation [BINENV_VERBOSE]
  ```
  
```
$ dive --help
This tool provides a way to discover and explore the contents of a docker image. Additionally the tool estimates
the amount of wasted space and identifies the offending files from the image.

Usage:
  dive [IMAGE] [flags]
  dive [command]
  ...
  ```
  
  With 1.19.3 version command w/o options work fine

**Comment by leucos** [comment]
Ah damn. This is a side effect of #212

**Comment by leucos** [comment]
v1.19.6 should solve this

**Comment by leucos** [comment]
`binenv update && binenv install binenv` tested here and fixes the issue.
Thanks for the heads up !

**Comment by eagafonov** [comment]
Hi,
I still have the issue with binenv 0.19.6 when run `binenv install --lock`

```
$> binenv version
binenv version 0.19.6 (built 2022-10-13T07:14:00Z)

$> echo helm=3.10.1 > .binenv.lock

$> binenv install --lock
This command will install one or several distributions with the specified versions. 
If --lock is used, versions from the .binenv.lock file in the current directory will be installed.
....

```

**Comment by leucos** [comment]
should be ok in v0.19.7-rc4

will test this and release v0.19.7
